#!/usr/bin/python3 -u
# Copyright 2020 Darius Neatu (neatudarius@gmail.com)

from check_utils.checks import checker_run
from check_utils.utils import log, run_and_measure
from datetime import timedelta
import sys

if __name__ == '__main__':
    language = None
    if len(sys.argv) > 1:
        if len(sys.argv) != 3 or sys.argv[1] != '-l' or sys.argv[2] not in ['c', 'py']:
            print("""
            Usage:
            # Run challenge for C & Python
            ./check

            # Run only for C
            ./check -l c

            # Run only for Python
            ./check -l py
            """)
            sys.exit(-1)
        language = sys.argv[2]

    ret, seconds = run_and_measure(lambda: checker_run(language))
    log('Total execution time: {}'.format(seconds))
